### ISSUE TITLE
Possibilità di rimuovere singoli corsi

### ISSUE THREAD

**Issue by albertoxamin** [fgaz/unitncal#1]
### Ad esempio i voglio togliere il corso Calcolatori Pari
![screen shot 2018-02-05 at 17 32 27](https://user-images.githubusercontent.com/6067659/35816265-929f55d0-0a9a-11e8-8a8b-7f5dbdc544dc.jpg)

**Questo è l'url con tutti i corsi**
```
https://easyroom.unitn.it/Orario/index.php?view=easycourse&include=corso&anno=2017&corso=0514G&anno2=P0005%7C1&date=05-02-2018&_lang=en&ar_codes_=EC145409_PARI_PALOP|EC145409_DISPARI_PALOP|EC145416_AGOST|EC145413_MOD1_RONCH_LEZ|EC145413_MOD2_KUPER_LEZ|EC145413_MOD1_RONCH_LAB|EC145413_MOD2_KUPER_LAB|EC145410_GHILO&ar_select_=true|true|true|true|true|true|true|true&all_events=1
```
Il corso che voglio cancellare è `EC145409_PARI_PALOP`, quindi rimuovendolo e adattando l'url diventa

```
https://easyroom.unitn.it/Orario/index.php?view=easycourse&include=corso&aa=2017&anno=2017&corso=0514G&anno2=P0005%7C1&date=05-02-2018&_lang=en&ar_codes_=EC145409_DISPARI_PALOP|EC145416_AGOST|EC145413_MOD1_RONCH_LEZ|EC145413_MOD2_KUPER_LEZ|EC145413_MOD1_RONCH_LAB|EC145413_MOD2_KUPER_LAB|EC145410_GHILO&ar_select_=true|true|true|true|true|true|true&all_events=1#
```

Passando quest'ultima stringa alla tua applicazione ottengo 
```
https://easyroom.unitn.it/Orario/ec_download_ical_list.php?form-type=corso&anno=2017&corso=0514G&anno2=P0005%7C1&ar_codes_=EC145409_DISPARI_PALOP%7CEC145416_AGOST%7CEC145413_MOD1_RONCH_LEZ%7CEC145413_MOD2_KUPER_LEZ%7CEC145413_MOD1_RONCH_LAB%7CEC145413_MOD2_KUPER_LAB%7CEC145410_GHILO&ar_select_=true%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue&dummyext.ics
```
sembra tutto ok fino a quando non lo aggiungo al calendario dove ho tutti corsi.

sto sbagliando qualcosa?

**Comment by fgaz** [comment]
Hey! Purtroppo quell'url (e easyroom in generale) è una cosa bruttissima... in pratica per gestire la visualizzazione dei corsi è necessario manipolare quella stringa di true|false|true, che corrispondono per ordine ai corsi indicati. Questo dovrebbe essere già gestito in automatico _se hai deselezionato i corsi prima di copiare l'url come da indicazioni_.
edit: deselezionato dalle checkbox di easyroom, in basso a destra
editedit: oops, vedo che hai già rimosso un true... strano, ora provo a vedere

Effettivamente potrebbe essere comodo riportare le checkbox anche in unitncal.fgaz.me e manipolare l'url direttamente da lì

**Comment by fgaz** [comment]
Ok, ho provato e non riesco a riprodurre il bug.

Il link di easyroom che io ho copiato è risultato questo:

```
view=easycourse&include=corso&aa=2017&anno=2017&corso=0514G&anno2=P0005%7C1&date=05-02-2018&_lang=en&ar_codes_=EC145409_PARI_PALOP%7CEC145409_DISPARI_PALOP%7CEC145416_AGOST%7CEC145413_MOD1_RONCH_LEZ%7CEC145413_MOD2_KUPER_LEZ%7CEC145413_MOD1_RONCH_LAB%7CEC145413_MOD2_KUPER_LAB%7CEC145410_GHILO&ar_select_=false%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue&all_events=1
```

e unitncal.fgaz.me lo hatrasformato in questo:

```
https://easyroom.unitn.it/Orario/ec_download_ical_list.php?form-type=corso&anno=2017&corso=0514G&anno2=P0005%7C1&ar_codes_=EC145409_PARI_PALOP%7CEC145409_DISPARI_PALOP%7CEC145416_AGOST%7CEC145413_MOD1_RONCH_LEZ%7CEC145413_MOD2_KUPER_LEZ%7CEC145413_MOD1_RONCH_LAB%7CEC145413_MOD2_KUPER_LAB%7CEC145410_GHILO&ar_select_=false%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue%7Ctrue&dummyext.ics
```

...che sembra escludere il corso dei pari

**Comment by fgaz** [comment]
Penso che il problema nell'url che hai modificato sia che non puoi escludere un corso rimuovendo il `true`, ma solo trasformandolo in `false` (che è quello che fanno le checkbox).

Se è risolto e non era un problema di unitncal chiudi pure.

Pensi che dovrei rendere più chiare le istruzioni per evitare futuri errori?

**Comment by albertoxamin** [comment]
Risolto grazie!
Si, se non metti le checkbox potresti scrivere un testo che spiega come fare.
