### ISSUE TITLE
Name of get method in link not working

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [fgaz/unitncal#6]
https://github.com/fgaz/unitncal/blob/04fe17644da9e1fbe8d51b2e6b191652b27e2099/convert.js#L19

`anno2` name has been changed to `anno2[]`.
So when a link is copied, now it contains `anno2%5B%5D`.
The problem is that JavaScript doesn't accept for some reasons
```javascript
"anno2%5B%5D": old_search["anno2%5B%5D"]
```
and neither with backslashes
```javascript
"anno2%5B%5D": old_search["anno2\%5B\%5D"]
```
Other ways to do it?

**Comment by fgaz** [comment]
I think the URI library I'm using already does an urldecode on the string, so just "anno2[]" should be ok. Try to print the object maybe?

**Comment by MarcoDiFrancesco** [comment]
With your solution is working. Now everything should be fine.
