### ISSUE TITLE
Easyacademy è cambiato ancora

### ISSUE THREAD

**Issue by ruggi99** [fgaz/unitncal#9]
Easyacademy è stato aggiornato ancora e adesso non include più la selezione dei corsi nell'URL...
Qualcuno può confermare?

**Comment by oselin** [comment]
Si me ne sono accorto anche io. Sembra che la selezione delle lezioni sia fatta attraverso js (mostrare o nascondere), infatti se da visualizzazione settimanale passi a quella di tutto il semestre i corsi deselezionati ricompaiono

**Comment by ruggi99** [comment]
Se clicchi su "Eventi ad elenco" invece viene aggiunta la selezione nell'URL come una volta ma sempre vuota

**Comment by oselin** [comment]
Allora dopo provo a dare un'occhiata. Nel frattempo ho notato che nel file .ics mancano alcuni parametri e per questo la sincronizzazione su Apple Calendar e Outlook falliva. Ho scritto allo staff per farglielo notare

**Comment by ruggi99** [comment]
A me il file .ics risulta vuoto (c'è l'intestazione con tanto di timezone ma nessun evento).
Poi non capisco perchè il timezone sia impostato su quello di Brussel..

**Comment by oselin** [comment]
Dopo ec_download_ical_list.php? manca il parametro view=easycourse
In questo modo:
https://easyacademy.unitn.it/AgendaStudentiUnitn/ec_download_ical_list.php?view=easycourse&include=corso&txtcurr=[...]

**Comment by ruggi99** [comment]
Ok, non solo manca `view=easycourse` ma anche `include=corso` per far popolare il file .ics, che ora "va".
(Non va la parte di selezione ancora)

**Comment by fgaz** [comment]
Pull requests per aggiungere i parametri necessari sono bene accette :)

**Comment by ruggi99** [comment]
Va bene fixare i due parametri mancanti, ma resta il problema della selezione dei corsi (che penso sia abbastanza importante?) ancora da fare

**Comment by oselin** [comment]
Ok allora ho dato un'occhiata. Cliccando sul pulsante per esportare in excel vengono nuovamente riempiti i parametri `ar_code_` e `ar_select_`, 

Quindi mettendo questi parametri "riempiti" all'interno del link per il file .ics si ottengono le lezioni filtrate.
Ma appunto perché si ottengono solo esportando in excel non penso ci sia modo di rendere automatica la conversione, va fatto a mano

**Comment by oselin** [comment]
Inoltre lo staff di easyacademy ha risposto che dovrebbero correggere il file .ics a breve, per cui sarà di nuovo possibile la sincronizzazione

**Comment by ruggi99** [comment]
C'è modo secondo voi di chiedere allo staff di rimettere la selezione dei corsi nell'URL?

**Comment by fgaz** [comment]
> ma resta il problema della selezione dei corsi

oh ok, ora ho visto...
il bello è che così si resetta pure la pagina, quindi è un problema anche per il sito. magari se come scrive @ruggi99 segnaliamo pure questo lo rimettono a posto

**Comment by ruggi99** [comment]
Appunto, perchè questo rende di fatto inutile il tuo sistema.
A meno che non si trovi un metodo, che io non ho trovato.
Ogni comando eseguito sul sito resetta l'URL perchè invece che fare affidamento sulla serializzazione del form (come una volta), prendono l'URL grezzo, modificano un parametro e poi ricaricano la pagina

**Comment by fgaz** [comment]
Oppure a questo punto si potrebbe chiedergli di esporre una volta per tutte in un campo di testo l'url dell'ics.

**Comment by ruggi99** [comment]
Più che esporlo in un campo di testo, forse sarebbe meglio copiarlo direttamente negli appunti con un click

**Comment by fgaz** [comment]
La soluzione con massima compatibilità di solito è avere entrambe le cose, come github:

![image](https://user-images.githubusercontent.com/8182846/93110381-c21d7000-f6a4-11ea-9990-05bdcec60d29.png)

**Comment by ruggi99** [comment]
Si certo :). Poi ovvio che uno se ne frega dell'URL generato e pensa solo a copiarlo col pulsante, no?
Comunque ho seri dubbi che lo faranno

**Comment by oselin** [comment]
Ok allora forse possiamo farcela ma in maniera "sporca".

Scriviamo uno script JS che che ottenga i meta-tag della legenda. Tra quest infatti sono presenti i `data-codice`, utilizzati nel "vecchio" link. Per cui basterebbe introdurre in unitncal delle checkbox per sapere se uno studente vuole visualizzare o meno un certo corso. Poi si compone il link per la richiesta del file .ics ed è fatta
![image](https://user-images.githubusercontent.com/57173644/93131232-0b38e880-f6d4-11ea-8b65-f23eed1e1c6a.png)

**Comment by ruggi99** [comment]
Sono d'accordo sull'idea.
Basta fare una chiamata a `https://easyacademy.unitn.it/AgendaStudentiUnitn/grid_call.php` che restituisce alcune informazioni in JSON, fra cui la legenda di cui sopra.
![image](https://user-images.githubusercontent.com/25064808/93174714-ba0a1280-f72e-11ea-877e-5bcfbee71a9c.png)

**Comment by oselin** [comment]
Grande!!

**Comment by ruggi99** [comment]
@fgaz @MarcoDiFrancesco osservazioni?

**Comment by MarcoDiFrancesco** [comment]
La soluzione con un dropdown per la selezione del corso di laurea e delle checkbox per la selezione dei corsi mi sembra una buona soluzione. Mi sorge comunque la domanda: che funzionalità avrebbe in più questo sistema a confronto di copiare il link del calendario direttamente da UniTrentoApp (Orari lezioni -> Preferite -> Top right icon -> Copia negli appunti)?

**Comment by oselin** [comment]
Ah cavolo non mi ero accorto di questo. Grazie 😉

**Comment by ruggi99** [comment]
L'App rende potenzialmente obsoleto questo sistema

**Comment by fgaz** [comment]
L'app se non ricordo male è software proprietario e non si appoggia a protocolli standard, il che non rende questo progetto ridondante.

Il problema a questo sito rimane comunque, quindi riapro, e se qualcuno ha una soluzione le PRs sono benvenute.

**Comment by ruggi99** [comment]
Ho chiuso l'issue per inattività, ma il problema persiste ovviamente.
Per curiosità Francesco, hai statistiche sull'utilizzo del tuo sito?

**Comment by fgaz** [comment]
Non le ho. Sono contrario a google analytics e simili per questioni di privacy, e preferisco semplicemente analizzare i log lato server per esempio con https://goaccess.io/. Per comodità tengo questo sito su netlify, in cui questa funzionalità è a pagamento, e non m'interessa abbastanza da abilitarla.

Il problema dovrebbe essere stato risolto in #10
